name: petrel
description: "海燕热更新框架"
version: 0.0.1
# homepage:

environment:
  sdk: ">=3.3.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  appwrite: ^15.0.0
  archive: ^4.0.5
  darty_json_safe: ^1.0.3
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  get: ^4.7.2
  path: ^1.9.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# platforms:
#   web:
